

USE master ;  
GO

CREATE DATABASE CURCLI  
ON   
( NAME = Sales_dat,  
    FILENAME = 'C:\BANCO\CURCLI.MDF',  
    SIZE = 10,  
    MAXSIZE = 50,  
    FILEGROWTH = 5 )  
LOG ON  
( NAME = Sales_log,  
    FILENAME = 'C:\BANCO\CURCLI.LDF',  
    SIZE = 5MB,  
    MAXSIZE = 25MB,  
    FILEGROWTH = 5MB )
    
    GO
   
use CURCLI

GO


CREATE TABLE DB_TELEFONES (
ID_TELEFONES		INT IDENTITY PRIMARY KEY,
NUM				VARCHAR (20),
DDI					INT,
DDD					INT,
NUMERO				VARCHAR (20),
COMPLEMENTO			VARCHAR (20),
HORARIO				VARCHAR (10))

GO

CREATE TABLE DB_NACION (
ID_NACION		INT PRIMARY KEY IDENTITY,
DESCR			VARCHAR (250),
ATIVO			INT)

GO

CREATE TABLE DB_ESTCIVIL (
ID_ESTCIVIL		INT IDENTITY PRIMARY KEY,
DESCRI			VARCHAR(150),
ATIVO			INT)

GO 

CREATE TABLE DB_ESCOL (
ID_ESCOL		INT IDENTITY PRIMARY KEY,
DESCR			VARCHAR(150),
ATIVO			INT)

GO

CREATE TABLE DB_SOUBE (
ID_SOUBE		INT IDENTITY PRIMARY KEY,
DESCR			VARCHAR(150),
TIVO			INT)
GO  


CREATE TABLE DB_CURCLI (
ID_CURCLI		INT IDENTITY PRIMARY KEY ,
NOME			VARCHAR (250),
DATANASC		DATETIME,
ID_NACION		INT,
ID_ESTCIVIL		INT,
ID_ESCOLA		INT,
ID_SEXO			INT,
ID_EMPREGO		INT,
ID_SOUBE		INT,
ID_DADOSCON		INT,
ATIVO			INT)


ALTER TABLE DB_CURCLI
ADD CONSTRAINT FK_DB_NACION FOREIGN KEY (ID_NACION)
REFERENCES DB_NACION(ID_NACION);

GO

ALTER TABLE DB_CURCLI
ADD CONSTRAINT FK_DB_ESTCIVIL FOREIGN KEY (ID_ESTCIVIL)
REFERENCES DB_ESTCIVIL(ID_ESTCIVIL);

GO


ALTER TABLE DB_CURCLI
ADD CONSTRAINT FK_DB_ESCOLA FOREIGN KEY (ID_ESCOLA)
REFERENCES DB_ESCOL(ID_ESCOL);

GO


ALTER TABLE DB_CURCLI
ADD CONSTRAINT FK_DB_SOUBE FOREIGN KEY (ID_SOUBE)
REFERENCES DB_SOUBE(ID_SOUBE);

GO

CREATE TABLE DB_PAIS (
ID_PAIS			INT PRIMARY KEY IDENTITY,
DESCRI			VARCHAR (150),
ATIVO			INT)

GO
CREATE TABLE DB_ESTADO(
ID_ESTADO		INT IDENTITY PRIMARY KEY,
DSCRI			VARCHAR (150),
ATIVO			INT) 

GO

CREATE TABLE DB_CIDADE(
ID_CIDADE		INT IDENTITY PRIMARY KEY,
DESCRI			VARCHAR (150),
ATIVO			INT)
GO
CREATE TABLE DB_BAIRRO (
ID_BAIRRO			INT IDENTITY PRIMARY KEY,
DESCR				VARCHAR(150),
ATIVO				INT)
GO

ALTER TABLE DB_CURCLI
ADD CONSTRAINT FK_DB_SOUBE FOREIGN KEY (ID_SOUBE)
REFERENCES DB_SOUBE(ID_SOUBE);


GO
CREATE TABLE DB_DADOSCON (
ID_DADOSCON		INT IDENTITY PRIMARY KEY,
ID_PAIS				INT,
CEP					VARCHAR(9),
ID_ESTADO				INT,
ID_CIDADE				INT,
ID_BAIRRO				INT,
ENDEREÇO			VARCHAR(150),
NUMERO				VARCHAR(10),
EMAIL				VARCHAR (150),
ID_TELEFONES		INT,
CONSTRAINT	FK_PAIS FOREIGN KEY (ID_PAIS) REFERENCES DB_PAIS (ID_PAIS),
CONSTRAINT FK_ESTADO  FOREIGN KEY (ID_ESTADO) REFERENCES DB_ESTADO (ID_ESTADO),
CONSTRAINT FK_CIDADE  FOREIGN KEY (ID_CIDADE) REFERENCES DB_CIDADE (ID_CIDADE),
CONSTRAINT FK_TELEFONES  FOREIGN KEY (ID_TELEFONES) REFERENCES DB_TELEFONES (ID_TELEFONES),
CONSTRAINT FK_BAIRRO  FOREIGN KEY (ID_BAIRRO) REFERENCES DB_BAIRRO(ID_BAIRRO))

GO


ALTER TABLE DB_CURCLI
ADD CONSTRAINT FK_DADOSCON FOREIGN KEY (ID_DADOSCON)
REFERENCES DB_DADOSCON(ID_DADOSCON);


